Repository NREL-Sienna/PowerSimulationsDynamics.jl, pull requests merged in 2020-08, with the labels that each got.

#19 Remove use of ext
  Project.toml
  src/PowerSimulationsDynamics.jl
  src/base/definitions.jl
  src/base/perturbations.jl
  src/base/simulation.jl
  src/base/simulation_initialization.jl
  src/base/simulation_inputs.jl
  src/base/supplemental_accesors.jl
  src/models/branch.jl
  src/models/device.jl
  src/models/kirchoff_laws.jl
  src/models/system.jl
  src/utils/plot_utils.jl
  test/utils/get_results.jl
Labels: enhancement

#22 Add AC1A model
  src/base/definitions.jl
  src/base/simulation.jl
  src/initialization/generator_components/init_avr.jl
  src/initialization/generator_components/init_machine.jl
  src/models/generator_models/avr_models.jl
  src/models/generator_models/machine_models.jl
  src/models/saturation_models.jl
  test/benchmarks/psse/AC1A/TEST_ESAC1A.csv
  test/benchmarks/psse/AC1A/TEST_ESAC1A_SAT.csv
  test/benchmarks/psse/AC1A/ThreeBusMulti.raw
  test/benchmarks/psse/AC1A/ThreeBus_ESAC1A.dyr
  test/benchmarks/psse/AC1A/ThreeBus_ESAC1A_SAT.dyr
  test/results/results_initial_conditions.jl
  test/test_case20_ac1a.jl
  test/utils/get_results.jl
Labels: enhancement

#23 improvements to core structs
  docs/src/Examples/example_OMIB.md
  docs/src/Examples/example_lines.md
  src/PowerSimulationsDynamics.jl
  src/base/definitions.jl
  src/base/simulation.jl
  src/base/simulation_initialization.jl
  src/base/simulation_inputs.jl
  src/base/small_signal.jl
  src/base/small_signal_results.jl
  src/utils/logging.jl
  src/utils/plot_utils.jl
  test/Project.toml
  test/test_case01_OMIB.jl
  test/test_case02_oneDoneQ.jl
  test/test_case03_simple_marconato.jl
  test/test_case04_marconato.jl
  test/test_case05_simple_anderson.jl
  test/test_case06_anderson.jl
  test/test_case07_5shaft.jl
  test/test_case08_DAIB.jl
  test/test_case09_oneDoneQ_inverter.jl
  test/test_case10_staticbranches.jl
  test/test_case11_dynbranches.jl
  test/test_case12_multimachine.jl
  test/test_case13_avrs.jl
  test/test_case14_inverter_ref.jl
  test/test_case15_genrou.jl
  test/test_case16_genroe.jl
  test/test_case17_genrou_avr.jl
  test/test_case18_gensal.jl
  test/test_case19_gensae.jl
  test/test_case20_ac1a.jl
  test/test_sundials.jl
Labels: breaking, enhancement

#25 Towards PSID 0.2
  src/initialization/generator_components/init_avr.jl
  src/models/generator_models/avr_models.jl
  src/models/generator_models/tg_models.jl
  src/models/saturation_models.jl
  test/Project.toml
  test/data_tests/dynamic_test_data.jl
Labels: Upstream
