Repository NREL-Sienna/PowerSimulationsDynamics.jl, pull requests merged in 2021-09, with the labels that each got.

#122 add docs about initialization
  docs/src/initialization.md
Labels: documentation

#136 fix droop control bug
  src/base/definitions.jl
  src/base/nlsolve_wrapper.jl
  src/base/simulation_initialization.jl
  src/initialization/init_device.jl
  src/initialization/inverter_components/init_frequency_estimator.jl
  src/initialization/inverter_components/init_inner.jl
  src/initialization/inverter_components/init_outer.jl
Labels: bug

#135 Add additional features and minor fixes
  docs/make.jl
  docs/src/quick_start_guide.md
  src/PowerSimulationsDynamics.jl
  src/base/simulation.jl
  src/base/simulation_initialization.jl
  src/base/simulation_inputs.jl
  test/test_base.jl
  test/test_case11_dynbranches.jl
Labels: enhancement
