Repository NREL-Sienna/PowerSimulationsDynamics.jl, pull requests merged in 2021-05, with the labels that each got.

#59 fix branch bug
  .github/workflows/master-tests.yml
  .github/workflows/pr_testing.yml
  Project.toml
  src/base/simulation_initialization.jl
  src/base/simulation_inputs.jl
  src/initialization/inverter_components/init_frequency_estimator.jl
  src/initialization/inverter_components/init_inner.jl
  src/models/inverter_models/inner_control_models.jl
  src/models/kirchoff_laws.jl
  src/models/system.jl
  test/Project.toml
  test/data_tests/dynamic_test_data.jl
  test/test_base.jl
Labels: bug

#62 Fixed typo in equations 1e and 1f of LCL Filter docs
  docs/src/component_models/filters.md
Labels: documentation

#66 Export Active and Reactive Power Series
  Project.toml
  src/PowerSimulationsDynamics.jl
  src/base/simulation_results.jl
  src/models/generator_models/machine_models.jl
  src/models/ref_transformations.jl
  src/post_processing/post_proc_common.jl
  src/post_processing/post_proc_generator.jl
  src/post_processing/post_proc_inverter.jl
  src/post_processing/post_proc_network.jl
  src/utils/plot_utils.jl
  test/test_case01_OMIB.jl
  test/test_case02_oneDoneQ.jl
  test/test_case03_simple_marconato.jl
  test/test_case04_marconato.jl
  test/test_case05_simple_anderson.jl
  test/test_case06_anderson.jl
  test/test_case08_DAIB.jl
  test/test_case15_genrou.jl
  test/test_case18_gensal.jl
Labels: enhancement
