Repository NREL-Sienna/PowerSimulationsDynamics.jl, pull requests merged in 2021-06, with the labels that each got.

#80 Missing imaginary unit in the docs
  docs/src/reference_frames.md
Labels: documentation

#83 Fix get initial conditions
  src/base/simulation_initialization.jl
Labels: bug

#84 add plot util for getting voltage angle
  src/PowerSimulationsDynamics.jl
  src/utils/plot_utils.jl
  test/test_case01_OMIB.jl
  test/test_case10_staticbranches.jl
  test/test_case11_dynbranches.jl
  test/test_case15_genrou.jl
  test/test_case16_genroe.jl
  test/test_case18_gensal.jl
  test/test_case19_gensae.jl
  test/test_case20_ac1a.jl
  test/x_test_sundials.jl
Labels: enhancement

#94 Add Grid Following docs
  docs/src/assets/sys_init.png
  docs/src/component_models/outer_control.md
Labels: documentation

#96 update docs
  docs/src/models.md
  docs/src/quick_start_guide.md
  test/Project.toml
Labels: documentation
