Repository NREL-Sienna/PowerSimulationsDynamics.jl, pull requests merged in 2022-08, with the labels that each got.

#261 remove jac sparsity heuristic
  src/base/jacobian.jl
  src/models/device.jl
  test/results/results_eigenvalues.jl
Labels: bug

#262 Add VOC model
  docs/src/component_models/outer_control.md
  src/initialization/inverter_components/init_inner.jl
  src/initialization/inverter_components/init_outer.jl
  src/models/inverter_models/outer_control_models.jl
  test/data_tests/dynamic_test_data.jl
  test/data_tests/test44.jl
  test/results/results_eigenvalues.jl
  test/results/results_initial_conditions.jl
  test/test_case44_voc.jl
Labels: New Features

#264 Add series branch flow
  src/PowerSimulationsDynamics.jl
  src/base/simulation_results.jl
  test/test_case26_SEXS.jl
Labels: enhancement
